name: Instant.potpvp
version: '${project.version}'
main: me.aiode.instant.potpvp.Instant.potpvp
api-version: 1.19
authors: [ iTrusty ]
description: Quick Load out for pvpers
website: https://pvp-mc.com/
commands:
  pvp:
    usage: /<command>
    description: It's not much but it'll do.
